---
title: "Unforced choice review"
author: "CS"
date: "26 8 2021"
output: pdf_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective

To review the psychological differences between forced-choice tasks (that force respondents to decide between options) and unforced- or nonforced-choice tasks (that allow for an "undecided" response).

To model the unforced-choice task so as to pinpoint these differences in the data.

## Review

### Task

There is relatively little methodological work on the unforced- or nonforced-choice task.

Early discussions in psychophysics are reviewed by @fernberger1930, who concludes that the original reasons to exclude "uncertain" responses (unstable responses, indicating and reflecting the underlying uncertainty, and associated with longer RT; mathematical difficulties of dealing with them) are no longer present and excluding them would be unscientific (Titchener).
He highlights that instructions determine whether a midpoint response is considered a failure to detect (eg., negative, failure to find a difference), or as a judgment of equality (ie, positive, detecting equality); the latter perhaps more subjective.
It is also suggested that adding the "undecided" option makes participants feel more comfortable with the task (see also Kaernbach).

@watson1973 compared a forced-choice with a nonforced choice task (which they describe as a 3-point scale, with an "undecided" option as the midpoint) and found the nonforced version to be equally well able to estimate discriminability (d').
The task was to decide in which of two time intervals the stimulus appeared.
In the nonforced variant, they varied the level of certainty that was to be required for a response (mildly, fairly, or very certain).
They modeled the data in a SDT framework, with the "undecided" region in the middle between the two stimulus distributions, and found that sensitivity (d') was at least as good (or even better) for the nonforced task versions, and was not influenced by the level of certainty.

@punch2001 compare forced- and nonforced-choice tasks in testing hearing aids, and found significantly more reliable estimates for the nonforced-choice task, and greater sensitivity of the nonforced-task data to experimental manipulations.

Unforced-choice tasks allow participants to express their uncertainty, instead of forcing them to guess or use heuristics; this can be helpful when one wants to minimize effects of guessing strategies/heuristics.
The sensitivity estimates are not affected by task format, In sum, there are few if any reasons against offering a third, midpoint or "undecided" option - except perhaps for the increased complexity of data analysis and modeling.

### Models

There are two modeling approaches for unforced-choice data, SDT and discrete-state.

The first is an SDT approach, as sketched by @watson1973, with an additional criterion and an "undecided" region in the middle.

@kaernbach2001 sketches a similar SDT model of the unforced-choice task and shows that the effect of introducing a criterion (as compared to the criterion-free forced-choice task), has only small effects on the psychometric function (in contrast to the criterion effects in forced-choice tasks).
Mainly, he applies a weighted-up-down-staircase procedure to the unforced-choice task and finds it performs better than the forced-choice version.

@garcía-pérez2011 compare estimation of the psychometric function via forced- and nonforced-choice tasks, find the nonforced-task preferrable, and discuss a general model of indecision.
They also point out that Fechner preferred the nonforced-choice (or three-point scale) format.
They have also recommended using catch trials...

This indecision model [@garcía-pérez2011] was applied eg.
in @garcía-pérez2013: "We show that asking observers to guess instead of allowing them to respond "uncertain" causes the confound described by Morgan et al. (2012). SDT models can indeed account for undecided cases and accommodate a three-response format. The first models of this type seem to be those of Treisman and Watts (1966; Treisman, 1973) and Watson, Kellogg, Kawanishi, and Lucas (1973), which were also used by Kaernbach (2001) to design a suitable adaptive psychophysical method (see also García-Pérez, 2002). A model of this type has been fully developed for 2AFC detection and discrimination tasks by GarcíaPérez and Alcalá-Quintana (2010a, 2010b, 2011b, 2012a; see also Alcalá-Quintana & García-Perez, 2011), and it is extended here for application to MSS. ... The purpose of this paper is to demonstrate the theoretical inability of MSS to distinguish response bias from perceptual effects and to discuss a simple and effective modification that can do so under some restrictive conditions. "

Morgan (2012) showed that the MSS psychometric function can be affected by response biases, without this becoming apparent or seoarable from a true psychmetric/sensitivity effeect.
With 3 response options, the MSS can however separate sensitivity effects from bias effects.

\
It is important to note that the valence-memory task is a MSS task, in that it presents only a single stimulus, and asks for a binary (or ternary) judgment - pleasant or unpleasant (or uncertain).
It is not a 2 AFC task in the sense that it does not present 2 stimuli among which the Ss has to choose.
Instead, it is similar to a rating task with three categories, with the midpoint reflecting uncertainty: "This decision space is analogous to that in the SDT model for a rating task with three categories (Macmillan & Creelman, 2005, their Figure 3.9)."\

-   The mSS task is inferior to an 2AFC task (with 3 response options) because the latter provides additional data (ie, a stimulus is presented in the first position on some trials and in the second on other trials) that allow separating guessing biases from perceptual effects.
    But given that the valence-memory assessment for a given CS cannot be reconstructed as a 2afc task ((except perhaps by asking ss to explicitly consider how strong their memory for the CS in the context of positive Uss is, compared to their memory for the CS in the context opf negative USS; a relatively convoluted task - how can we be sure that Ss retrieve the former, then the latter, and then compare? Only if we ask for both judgments, then we could also control the order...).
    In the valmem task, the stimulus is the CS, and the observer judges the retrieved memory (ie, summary valence of the echo).
    An alternative would be to separately evaluate memory strength in the context of positive as well as of negative Uss.
    This might be closer to a 2afc memory task - where the perceptual „signal" is replaced by a mnemonic signal. Probably difficult to do for participants; most likely the only valid data will be when individual US identites can be retrieved...)

-   The MSS task with three resopnse options (ie, including an undecided option) is able to dissociate psychological and response effects, under the assumptions of (1) a symmetric indecision region, and (2) that all cases of uncertainty are correctly indicated (ie, no residual guessing biases).
    These assumptions cannot be tested within the model, and are relatively strong.

-   On the other hand, similarly strong assumptiosn are made in the MPT model: that (1\`) processes are invariant across inclusion and exclusion, and (2) all cases of the absence of memory are detected by the participant and adequately dealt with as instructed (e.g., reverse responses under exclusion instructions).

-   What can the model help us do?
    Draw psychometric functions

    -   Calculate d' and bias?
    -   S

\@sridharan extend this SDT approach to a two-dimensional decision space (i.e., when the evidence varies on two dimensions, similar to source-memory SDT models).
They compare both approaches in two studies and found them to be equally well able to model the data in one study, and found the twodimensional version to be preferred in another.

The second is a discrete-state modeling approach:

Hsu and Doble have proposed a Luce-Krantz threshold model with three states: nondiscriminable, discriminable, and certainly discriminable.
They applied it to a task with 2, 3, or 4 options and compared them.
They found that subjects differ in how much they use the "uncertain" option across latent states.

...

@ingleby_1973 develop models of forced-choice tasks and only discuss a nonforced version in passing.

In the choice literature (e.g., Scott et al., Veldwijk et al.) discuss reasons related to prospect theory and marginal returns for offering a third default (status quo) option.

In psychophysics, the combination of task and staircase has been investigated (Hatzfeld et al), with unclear results.

Yi and Merfeld have looked at models including confidence ratings, in addition to binary choice, and developed a model that makes use of confidence data to more efficiently estimate a psychometric function.

## Application to valence judgments versus valence-memory tasks

In decisions about valence, participants are often asked to judge an option as pleasant or unpleasant with two or more response categories, sometimes including a midpoint (i.e., an uneven number of categories).
Here, a choice of the midpoint response category indicates a neutral evaluation, neither pleasant nor unpleasant, not uncertainty about one's evaluative judgment.
This differs from its meaning in memory tasks, where they are used to indicate such judgment uncertainty.

In a valence-memory task, participants are asked to indicate the valence of the US stimuli paired with a given CS.
Here, the correct response can be either "pleasant" or "unpleasant".
If participants cannot remember US valence, in a forced-choice task they would have to guess one of those two options.
Such guesses may be given with equal probability, in which case they would do little harm, except perhaps reducing the reliability of the measure.
In other cases, guesses may instead be biased by the evaluation of the given CS stimulus (i.e., participants respond (un)"pleasant" if they (dis)like the CS; e.g., @Bar-Anan et al., 2014) and thereby artificially increase the relationship between measured evaluation and valence memory (Gawronski & Walther; Hütter et al.).
Thus, forcing participants to make a choice may bias the resulting measure.

Unforced-choice tasks can therefore be expected to largely eliminate the detrimental biasing effect of heuristics used under uncertainty: If participants are allowed to indicate that they do not remember (e.g., by selecting a third "uncertain" response option), they are no longer forced to guess.
In addition, the proportion of "uncertain" responses will inform researchers about the proportion of guessing-based responses in a parallel forced-choice task (and thereby about the potential magnitude of the bias problem).

## Models of the unforced-choice valence-memory task (UCVM)

One way to model the UCVM task is to draw on the analogy with a "method of single stimuli" (MSS) task as described and compared to AFC tasks by Garcia-Perez 2013.
In the context of psychophysics, the MSS task presents a single stimulus and asks participants to respond to one of its attributes with one of two options.
This is contrasted with strict AFC tasks, which present two stimuli and ask participants to compare them.

However, the perceptual decisions required in the MSS and AFC tasks are somewhat at odds with the mnemonic decisions required in the UCVM task: In the former, the to-be-judged information is in the stimulus (or its immediate perception), whereas in the latter, the information first has to be retrieved from memory.
Retrieval from memory may occur in different ways, two of which will be discussed below.

### Memory retrieval as ratings of "mean context pleasantness"

One way to conceive of memory retrieval is close to the perceptual case: The requested attribute of the presented CS may be directly retrieved and judged.
The relevant attribute, in the present context, might be conceived of as the mean pleasantness of the contexts in which the CS appeared; if this exceeds some criterion, then the "pleasant" response is given.

### Memory retrieval as source memory

Another way is to draw on the analogy to source memory paradigms, in which a single memory cue is presented, and participants are asked to indicate with which of two sources it appeared during the learning phase.
With one source being "pleasant USs" and another "unpleasant USs", this directly maps onto the UCVM task.
In source memory tasks, participants are asked to evaluate their source memory, which can be conceived of as a single-dimensional strength variable ("the degree to which the distribution of Source A and Source B items can be discriminated from each other", Slotnick et al., 2000; see also Banks, 2000).
The two different item classes (i.e., those from source A vs. B) are represented by different distributions on this dimension.

## Problematic effects of potential heuristics on conclusions in EC research

Hütter et al. have pointed out the possibility that such biases exist, and that if they do, they would mask true unaware EC effects.
If participants, under uncertainty, resort to a "feeling-as-information" heuristic, they would use their feelings towards the CS as information about the valence of the USs paired with it.
That is, even when they were unaware of the US's valence, and therefore do not remember it, they may nevertheless report the correct US valence because it may have unconsciously influenced their feelings towards the CS, which in turn may have biased their memory judgments.

Importantly, this criticism applies only to a forced-choice version of the valence-memory task.
In an unforced-choice task, participants are no longer forced to guess under uncertainty, they can simply indicate that they are uncertain.
Thus, assuming participants readily report their uncertainty, they should no longer feel the need to resort to guessing heuristics, and a feeling-as-information heuristic should no longer bias the results.
When they do not remember US valence, participants can readily report their absence of memory using the "uncertain" response.
Assuming for a moment that absence of memory indicates lack of awareness during learning, these "uncertain" cases are critical for testing whether unaware EC indeed exists.
In three studies, Stahl et al. (2009) have found no evidence for EC in these cases, neither on a self-report measure nor in an affective priming task.

## Evidence for two different heuristics

Bar-Anan and co-workers (2010, 2014) found that participants indeed use CS evaluations to inform their judgments about US valence memory.
In their (2010) Experiment 2, the memory task asked participants to indicate on a 6-point scale whether a given CS was paired with pleasant (one end) or unpleasant images (the other end), with rating extremity indicating confidence (certainly, probably, guess).
It id not involve a midpoint response to indicate uncertainty.
Yet, uncertainty may be reflected in the guess responses, which should more strongly reflect the heuristic than the certain responses.
However, the authors did not analyze confidence separately from accuracy, so it is not possible to say whether the heuristic was used especially under uncertainty, or especially when certain; or equally across all levels of confidence.

In their 2014 paper, they found evidence for a bias that applies especially under certainty: ...
